- type: job
  id: Sheriff
  name: job-name-sheriff
  description: job-description-sheriff
  playTimeTracker: JobHeadOfSecurity
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 216000 # 60 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 172800 # 48 hours
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 43200 # 12 hours
  whitelisted: true
  startingGear: SheriffGear
  alwaysUseSpawner: true
  icon: JobIconSheriff
  requireAdminNotify: true
  supervisors: job-supervisors-centcom
  weight: 180
  displayWeight: 70
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: SheriffGear
  equipment:
    pocket1: WeaponPistolMk58 #WeaponPistolMk58Nonlethal
    pocket2: WeaponEnergyGunMultiphase # DeltaV gun
  storage:
    back:
    - NfsdTechFabFlatpack
    - Multitool
    - HoloprojectorNfsd
    - DoorRemoteNfsd
    - BaseSecurityUplinkRadioSheriff
    - RubberStampSheriff
